.. _Sphinx: https://www.sphinx-doc.org/

.. |abcdoc| replace:: *abcdoc*
.. |bug_reports| replace:: https://github.com/i386x/abcdoc/issues
.. |source| replace:: https://github.com/i386x/abcdoc
.. |sphinx| replace:: `Sphinx`_

..
   Configuration:

.. |abcdoc_debug| replace:: ``abcdoc_debug``
.. |html_permalinks| replace:: ``html_permalinks``
.. |html_permalinks_icon| replace:: ``html_permalinks_icon``

..
   Document nodes:

.. _document node: https://docutils.sourceforge.io/docs/ref/doctree.html
.. _toctree: :directives:`directive-toctree`

.. |bullet_list| replace:: ``docutils.nodes.bullet_list``
.. |comment| replace:: ``docutils.nodes.comment``
.. |compact_paragraph| replace:: ``sphinx.addnodes.compact_paragraph``
.. |compound| replace:: ``docutils.nodes.compound``
.. |document| replace:: document
.. |document node| replace:: `document node`_
.. |list_item| replace:: ``docutils.nodes.list_item``
.. |paragraph| replace:: ``docutils.nodes.paragraph``
.. |reference| replace:: ``docutils.nodes.reference``
.. |section| replace:: ``docutils.nodes.section``
.. |substitution_definition| replace::
       ``docutils.nodes.substitution_definition``
.. |target| replace:: ``docutils.nodes.target``
.. |title| replace:: ``docutils.nodes.title``
.. |toctree| replace:: `toctree`_
.. |Node| replace:: ``docutils.nodes.Node``
.. |Text| replace:: ``docutils.nodes.Text``

..
   Third party classes and functions:

.. _default priority: https://docutils.sourceforge.io/docs/ref/transforms.html

.. |default priority| replace:: `default priority`_

.. |BuildEnvironment| replace:: :class:`~sphinx.environment.BuildEnvironment`
.. |Builder| replace:: :class:`~sphinx.builders.Builder`
.. |Config| replace:: :class:`~sphinx.config.Config`
.. |EventManager| replace:: :class:`~sphinx.events.EventManager`
.. |Sphinx| replace:: :class:`~sphinx.application.Sphinx`
.. |SphinxComponentRegistry| replace::
       :class:`~sphinx.registry.SphinxComponentRegistry`

..
   :mod:`~sphinx_abcdoc_theme.writer`:

.. |check_ids| replace:: :func:`~sphinx_abcdoc_theme.writer.check_ids`
.. |get_id| replace:: :func:`~sphinx_abcdoc_theme.writer.get_id`
.. |ids2str| replace:: :func:`~sphinx_abcdoc_theme.writer.ids2str`
.. |is_index| replace:: :func:`~sphinx_abcdoc_theme.writer.is_index`
.. |is_partial_node| replace::
       :func:`~sphinx_abcdoc_theme.writer.is_partial_node`
.. |node_source| replace:: :func:`~sphinx_abcdoc_theme.writer.node_source`
.. |tag_attr| replace:: :func:`~sphinx_abcdoc_theme.writer.tag_attr`

.. |Context| replace:: :class:`~sphinx_abcdoc_theme.writer.Context`
.. |Context.check_identity| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.check_identity`
.. |Context.check_node_stack| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.check_node_stack`
.. |Context.check_scope_stack| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.check_scope_stack`
.. |Context.check_section_stack| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.check_section_stack`
.. |Context.contribute| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.contribute`
.. |Context.get_content| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.get_content`
.. |Context.get_section_id| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.get_section_id`
.. |Context.get_section_level| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.get_section_level`
.. |Context.in_scope| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.in_scope`
.. |Context.pop_node| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.pop_node`
.. |Context.pop_scope| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.pop_scope`
.. |Context.pop_section| replace::
       :meth:`~sphinx_abcdoc_theme.writer.Context.pop_section`
.. |HTML translator| replace::
       :class:`HTML translator <sphinx_abcdoc_theme.writer.HtmlTranslator>`
.. |HtmlTranslator| replace::
       :class:`~sphinx_abcdoc_theme.writer.HtmlTranslator`
.. |HtmlTranslatorBase| replace::
       :class:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase`
.. |HtmlTranslatorBase.__getattr__| replace::
       :meth:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase.__getattr__`
.. |HtmlTranslatorBase.__init__| replace::
       :meth:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase.__init__`
.. |HtmlTranslatorBase.add_title| replace::
       :meth:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase.add_title`
.. |HtmlTranslatorBase.contribute| replace::
       :meth:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase.contribute`
.. |HtmlTranslatorBase.ship_body| replace::
       :meth:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase.ship_body`
.. |HtmlTranslatorBase.start_tag| replace::
       :meth:`~sphinx_abcdoc_theme.writer.HtmlTranslatorBase.start_tag`

..
   :mod:`~sphinx_abcdoc_theme.utils`:

.. |html_escape| replace:: :func:`~sphinx_abcdoc_theme.utils.html_escape`
.. |indent_text| replace:: :func:`~sphinx_abcdoc_theme.utils.indent_text`
.. |indentation| replace:: :func:`~sphinx_abcdoc_theme.utils.indentation`
.. |log_node_end| replace:: :func:`~sphinx_abcdoc_theme.utils.log_node_end`
.. |log_node_start| replace:: :func:`~sphinx_abcdoc_theme.utils.log_node_start`
.. |tagname| replace:: :func:`~sphinx_abcdoc_theme.utils.tagname`
.. |tokenize| replace:: :func:`~sphinx_abcdoc_theme.utils.tokenize`
.. |wrap| replace:: :func:`~sphinx_abcdoc_theme.utils.wrap`

.. |FileAsset| replace:: :class:`~sphinx_abcdoc_theme.utils.FileAsset`
