.. _Sphinx: https://www.sphinx-doc.org/

.. |abcdoc| replace:: *abcdoc*
.. |bug_reports| replace:: https://github.com/i386x/abcdoc/issues
.. |source| replace:: https://github.com/i386x/abcdoc
.. |sphinx| replace:: `Sphinx`_

..
   Configuration:

.. |abcdoc_debug| replace:: ``abcdoc_debug``
.. |html_permalinks| replace:: ``html_permalinks``
.. |html_permalinks_icon| replace:: ``html_permalinks_icon``

..
   Document nodes:

.. _document node: https://docutils.sourceforge.io/docs/ref/doctree.html
.. _toctree: :directives:`directive-toctree`

.. |bullet_list| replace:: ``bullet_list``
.. |compact_paragraph| replace:: ``compact_paragraph``
.. |compound| replace:: ``compound``
.. |document| replace:: document
.. |document node| replace:: `document node`_
.. |list_item| replace:: ``list_item``
.. |paragraph| replace:: ``paragraph``
.. |reference| replace:: ``reference``
.. |section| replace:: ``section``
.. |substitution_definition| replace:: ``substitution_definition``
.. |target| replace:: ``target``
.. |title| replace:: ``title``
.. |toctree| replace:: `toctree`_
.. |Node| replace:: :class:`~docutils.nodes.Node`
.. |Text| replace:: ``Text``

..
   Third party classes and functions:

.. _default priority: https://docutils.sourceforge.io/docs/ref/transforms.html

.. |default priority| replace:: `default priority`_
.. |HTML translator| replace::
       :class:`HTML translator <sphinx_abcdoc_theme.writer.HtmlTranslator>`

..
   :mod:`~sphinx_abcdoc_theme.utils`:

.. |html_escape| replace:: :func:`~sphinx_abcdoc_theme.utils.html_escape`
.. |indent_text| replace:: :func:`~sphinx_abcdoc_theme.utils.indent_text`
.. |indentation| replace:: :func:`~sphinx_abcdoc_theme.utils.indentation`
.. |log_node_end| replace:: :func:`~sphinx_abcdoc_theme.utils.log_node_end`
.. |log_node_start| replace:: :func:`~sphinx_abcdoc_theme.utils.log_node_start`
.. |tagname| replace:: :func:`~sphinx_abcdoc_theme.utils.tagname`
.. |tokenize| replace:: :func:`~sphinx_abcdoc_theme.utils.tokenize`
.. |wrap| replace:: :func:`~sphinx_abcdoc_theme.utils.wrap`

.. |FileAsset| replace:: :class:`~sphinx_abcdoc_theme.utils.FileAsset`
.. |FileAsset.__subclasshook__| replace:: :meth:`FileAsset.__subclasshook__()
       <sphinx_abcdoc_theme.utils.FileAsset.__subclasshook__>`
.. |FileAsset.filename| replace:: :attr:`FileAsset.filename
       <sphinx_abcdoc_theme.utils.FileAsset.filename>`
